### PR TITLE
Clean headers to only use timer 4 pins

### PR DESCRIPTION
**Pull request by photodude**
Follows Timer 5 changes in preparation for library version v1.1
New test is copied from VincentLim/TimerFive but is untested.

### CODE REVIEW

**Comment by VincentLim** [comment]
Thanks Walt, 
One little thing more if you don't mind : I had an issue on timerFive concerning examples naming : 
https://github.com/VincentLim/TimerFive/pull/3
Could you rename folder according to .ino file ?

PS : TestTimer4.ino tested and working :+1:

**Comment by photodude** [comment]
@VincentLim 🤦‍♂️ I should have remembered that file/folder naming requirement. Fixed now.

**Comment by VincentLim** [comment]
thanks

**Comment by photodude** [comment]
Thank you @VincentLim

**Pull request merged**
